### PR TITLE
Added capistrano configuration for raschpi

### PR DESCRIPTION
**Pull request by panmari**
Publishing is only possible if you're on VPN, but that can be changed easily if necessary.

### CODE REVIEW

**Comment by panmari** [comment]
Explanation:

Capistrano should help with deploying. It makes it possible to load a given revision to a server, check it out there, precompile assets automatically and everything else necessary in production mode with only one command:

```
cap production deploy
```

**Comment by misch** [comment]
In http://capistranorb.com/documentation/getting-started/preparing-your-application/ it's recommended to take config/database.yml out of the repository. Should we do that...? I have absolutely no experience with Capistrano or deploying Apps in general...

**Comment by panmari** [comment]
Correct, but I went another way and added the gem `dotenv`. This is used to store our secrets, i. e. the database pw and secrets.yml-kez in a file called `.env` in the rails root for production. The password is then read out like an environment variable, visible [here](https://github.com/misch/gpCollect/blob/master/config/database.yml#L85) and [here](https://github.com/misch/gpCollect/blob/master/config/secrets.yml#L22)

This has the advantage that the configuration is now decoupled from our secrets. We have as much as possible of the configuration in the repository, so we need to remember/do by hand as little as possible.

**Comment by misch** [comment]
Ok, after reading a bit and your explanations, I trust this PR. ;-)

**Pull request merged**
